/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class openKinectv2_Device */

#ifndef _Included_openKinectv2_Device
#define _Included_openKinectv2_Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     openKinectv2_Device
 * Method:    initJNI
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_openKinectv2_Device_jniInit
  (JNIEnv *, jobject);

/*
 * Class:     openKinectv2_Device
 * Method:    openJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openKinectv2_Device_jniOpen
  (JNIEnv *, jobject);
    
/*
 * Class:     openKinectv2_Device
 * Method:    openJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openKinectv2_Device_jniOpenM
(JNIEnv *, jobject, jint index);
    
/*
 * Class:     openKinectv2_Device
 * Method:    stopJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openKinectv2_Device_jniStop
(JNIEnv *, jobject);
    
/*
 * Class:     openKinectv2_Device
 * Method:    stopJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openKinectv2_Device_jniEumerateDevices
(JNIEnv *, jobject);

/*
 * Class:     openKinectv2_Device
 * Method:    openJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_openKinectv2_Device_jniOpenSerial
(JNIEnv *, jobject, jint );
    
    
/*
 * Class:     openKinectv2_Device
 * Method:    etNumDevices
 * Signature: ()V
 */
JNIEXPORT jint JNICALL Java_openKinectv2_Device_jniGetNumDevices
    (JNIEnv *, jobject);
    
    
/*
 * Class:     openKinectv2_Device
 * Method:    etNumDevices
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_openKinectv2_Device_jniGetSerialDevice
(JNIEnv *, jobject, jint );
    

/*
 * Class:     openKinectv2_Device
 * Method:    jniGetDepthData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_openKinectv2_Device_jniGetDepthData
  (JNIEnv *, jobject);
    
/*
 * Class:     openKinectv2_Device
 * Method:    jniGetDepthData
 * Signature: ()[I
 */
    
JNIEXPORT jintArray JNICALL Java_openKinectv2_Device_jniGetRawDepthData
(JNIEnv *, jobject);
    
    
/*
 * Class:     openKinectv2_Device
 * Method:    jniGetDepthData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_openKinectv2_Device_jniGetIrData
(JNIEnv *, jobject);

/*
 * Class:     openKinectv2_Device
 * Method:    jniGetDepthData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_openKinectv2_Device_jniGetColorData
(JNIEnv *, jobject);
    
/*
 * Class:     openKinectv2_Device
 * Method:    jniGetDepthData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_openKinectv2_Device_jniGetUndistorted
(JNIEnv *, jobject);


/*
 * Class:     openKinectv2_Device
 * Method:    jniGetDepthData
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_openKinectv2_Device_jniGetRegistered
(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
